name = "sistem-nomor-pkrs"
compatibility_date = "2024-03-20"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "db_pkrs"
database_id = "af54e461-bf27-4161-9c7f-4523e30154aa"